export const courtConstants = {
  ADD_PLAYER: "ADD_PLAYER",
  REMOVE_PLAYER: "REMOVE_PLAYER",
  SET_PLAYERS: "SET_COURT_PLAYERS",
  SET_MATCHES: "SET_MATCHES",
  MIX_PLAYERS: "MIX_PLAYER",
  UPDATE_PLAYERS: "UPDATE_PLAYERS",
  SET_SESSION_ID: "SET_SESSION_ID"
};
