export const matchStatusConstants = {
  WAIT_TO_START: "WAIT_TO_START",
  REGULAR_TIME: "REGULAR_TIME",
  FINAL_ATTACK: "FINAL_ATTACK",
  EXTRA_TIME: "EXTRA_TIME",
  EXTRA_TIME_STARTED: "EXTRA_TIME_STARTED",
  EXTRA_TIME_FINAL_ATTACK: "EXTRA_TIME_FINAL_ATTACK",
  SHOW_PENALTIES: "SHOW_PENALTIES",
  SHOW_END_MATCH: "SHOW_END_MATCH",
  SHOW_MATCH_SUMMRY: "SHOW_MATCH_SUMMRY",

  PENALTIES: "PENALTIES",
  CHANGE_STATUS: "CHANGE_STATUS"
};
